### ISSUE TITLE
Get the tenant while in the Global.asax or Startup.cs

### ISSUE THREAD

**Issue by JoeWarwick** [saaskit/saaskit#14]
Hi mate!
I hope you can help me. Im using SaaSkit with an asp.net mvc project.

I'm not using Nancy as I don't want to rewrite all my controller code.

I would like to add the tenant name into the ViewEngines view locator, but this is best to do in the application_start phase of the bootstrapping and the HttpContext here cannot get the current tenant id as it does not resolve yet.

Can you advise whether it will be possible to get the tenant at application_start phase so that view search locations may be initialised using the tenant data?

Thanks heaps. This is a great system and got it all working so far except for this..

Regs.

**Comment by benfoster** [comment]
Hey Joe,

You can't get the tenant in application_start because this is only called once per application lifetime.

The way to do this is to pass a `Func<HttpContextBase, TenantContext<YourTenant>>` to your view engine. This way you can invoke this function on each request.

You can find an example of something similar [here](https://github.com/benfoster/Fabrik.Common/blob/master/src/Fabrik.Common.Web/ViewEngines/ThemeableVirtualPathProviderViewEngine.cs) where I'm resolving the current site (effectively tenant) to get a theme.
