### ISSUE TITLE
Asp.Net Core RC2 support

### ISSUE THREAD

**Issue by MaximBalaganskiy** [saaskit/saaskit#25]
The package references need to be updated

**Comment by rdefreitas** [comment]
Already started taking a stab at this. It's more than just the package references...

**Comment by MaximBalaganskiy** [comment]
:+1: Totaly understand. I've copied the main project to make it work in my project. At first, I wanted to suggest a pull request, but there are also tests... which I don't really have time for...

**Comment by rdefreitas** [comment]
The migration guide here only skims the tip of the iceberg:
https://docs.asp.net/en/latest/migration/rc1-to-rc2.html

Since I'm making heavy use of saaskit in a new project I've been working on (thanks @benfoster !), I put some time in to this earlier today.  I'm hoping to submit a pull request in a couple of hours.

**Comment by NinoFloris** [comment]
Nice, yeah I have a fork running on RC2 for a while now but I haven't taken a stab at the samples, the tests are running OK though

https://github.com/crowded/saaskit/

**Comment by rdefreitas** [comment]
@NinoFloris can you close this issue? RC2 is now fully supported, samples and all.

**Comment by NinoFloris** [comment]
I'm sorry I cannot, as it is not my issue
