### ISSUE TITLE
MemoryCache eviction issue with multiple identifiers 

### ISSUE THREAD

**Issue by NinoFloris** [saaskit/saaskit#27]
When the memory cache evicts an identifier it disposes the TenantContext.
However there are no guard rails that it is the only identifier that used this TenantContext and as long as these cache entries stay warm, then these entries keep returning a disposed TenantContext.

I have fixed this in https://github.com/crowded/saaskit/commit/5e6897acc661acaf9fa0f878ede04e5e51edd349
For now but I have a few other ideas of dealing with this issue that might be neater.  

EDIT:
It was late and I hadn't tested it through 'assumption is the...' ...
Your cache classes (ITenantResolver) are no singletons because you expect library users to only build it the MemoryCache way (or any other non direct cache object). Because otherwise you would have reasoned that this call might not have been the greatest to do if we are talking about classes that users might try to use for caching
```cs
// No singleton?! for cache classes?! 
services.AddScoped<ITenantResolver<TTenant>, TResolver>();
```
The next discovery was that right when I though I could just change this line it dawned on me that my own subclass of MemoryCacheResolver (which implements this ITenantResolver) rely on db connection's getting injected into them as an extra constructor argument so a singleton is out of the question as fresh/working connections are quite useful.

Then I thought ok lets do it like my proposed option 1. which then reminded me why I was so turned off by this solution in the first place as I now also need to add in my TenantIdentifiers while constructing the TenantContext... Ewhhh, and I thought it was gross already that I as a user even had to create the TenantContext in the first place.

Too many edge cases in the current implementation, the abstraction is wrong.

Ok rant is over, time to go to bed and rewrite this in the morning to the sane option 3. the dual layer model.
This gives you the minimum implementation burden as a library user and maximum control over the (optional) caching layer and other parts of the pipeline as the library author.

**Comment by benfoster** [comment]
A temporary fix for this is to override `CreateCacheEntryOptions` and use absolute expiration. This will ensure that all the cache entries expire at the same time.

A better solution would be to set cache dependencies between the cache entries - I know this was a feature of MemoryCache in ASP.NET 4.6 but not sure about Core. 

Another option worth discussing is whether it's acceptable to nominate a *primary* identifier. If this was the case we can ensure that only evicting the primary identifier would dispose the tenant context.

Let's keep the discussion going. I'd be interesting to hear how you're using this feature. I originally created it because we support multiple domain names per tenant but each tenant can only have one primary domain. We then have additional middleware that redirects to the primary domain if necessary.

**Comment by NinoFloris** [comment]
Me too, exactly the same usecase. Please check the code, it now uses the tenantcontext guid as cache key

**Comment by rdefreitas** [comment]
@benfoster, RC2 does indeed allow you to create cache dependencies using eviction tokens.

**Comment by rdefreitas** [comment]
BTW, @NinoFloris, I'm curious as to what you're pulling back with your tenant that you perceive as very expensive...

Are you pulling in the entire aggregate graph of the tenant, or just a stripped down data model that gives you the basic relevant data for each request?

**Comment by NinoFloris** [comment]
I use it as a lazy initializer for a lot of tenant state, setting up a
container with specific configs from the database, loading modules,
etcetera. That means an extra 500ms to 1,5s easy. This gets rooted in the
TenantContext.
