### ISSUE TITLE
Identity Cookie and multi tenancy

### ISSUE THREAD

**Issue by dazinator** [saaskit/saaskit#43]
I was wondering whether it was possible to use saaskit with identity in such a way that each tenant has its own application sign in cookie. 
During startup, in configureservices(), when you AddIdentity() you can configure the cookie details (its name, the domain etc) however it doesnt appear you can configure identity for multiple seperate domains. I'm wondering if anyone has tried the structuremap approach perhaps with identity, so that identity is configured per tenant?

**Comment by joeaudette** [comment]
for separate domains you already have cookie isolation in the web browser so it doesn't matter if they use the same name, they would always be separate cookies per domain

you can of course set different name and other properties per tenant, but the challenge of it with identity is that identity uses 

```
IOptions<IdentityOptions> 
```

to pass properties such as cookieoptions like authscheme to the authentication middleware and IOptions<IdentityOptions> is a singleton so you don't naturally get a different one per tenant

In my [cloudscribe Core project](https://github.com/joeaudette/cloudscribe) I have implemented multi tenant identity that enables resolving different IdentityOptions per tenant. This is done with a custom implementation of 

```
IOptions<IdentityOptions>
```

https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Identity/SiteIdentityOptionsResolver.cs so even though the IOptions itself is a singleton the value it returns is resolved per request so that it can return tenant specific IdentityOptions.

In addition to host/domain name tenants my project also supports mutliple tenants in a single host/domain name using the first folder segment of the url. In that case there is no web browser cookie isolation so it is important for the tenants to have different cookie names. and it works.

Note that I'm using a custom identity implementation such that identity objects like UserStore, RoleStore, SignInManager, UserManager are all tenant aware, they have the tenant resolved from the request and use the tenantid aka siteid as a parameter when looking up data such as users.

You can study the [Startup.cs](https://github.com/joeaudette/cloudscribe/blob/master/src/example.WebApp/Startup.cs) in the example.WebApp of my solution and other code in my project that may also be informative for you.

**Comment by dazinator** [comment]
> for separate domains you already have cookie isolation in the web browser so it doesn't matter if they use the same name, they would always be separate cookies per domain

Yeah it's not really the cookie name I need to configure, it's that I need to a cookie per top level domain. My site is accessed on:
- one.foo.com
- two.foo.com
- one.bar.com
- two.bar.com

So, the challenge is to try and configure asp.net identity to use a cookie with domain ".foo.com" and a cookie with domain ".bar.com" so that when a user navigates from `one.foo.com` to `two.foo.com` the cookie is kept and they don't have to sign in again! The problem is that it looks like you can only configure a single `IdentityOptions`..

> In my cloudscribe Core project I have implemented multi tenant identity that enables resolving different IdentityOptions per tenant. 

Ahh nice one! I think this is what I would need then.. I did notice that saaskit lets you configure services per tenant though, so I thought perhaps this would allow you to register a different `IdentityOptions` per tenant.. I might just experiment with that quickly also.

Thank you very much for your help!

**Comment by dazinator** [comment]
Thanks @joeaudette - I have managed to get this working now. Your code really helped a lot, it was invaluable.

**Comment by learntecno** [comment]
@joeaudette  I need some help on this, I am using **SAASKIT + Identity Server4** , It's working fine,
configured multi tenant by  http://localhost:5001 and http://localhost:5002 ,the issue is when I logged in site http://localhost:5001 , in http://localhost:5002 is not prompting for login , it says already logged in
even I used the UsePerTenant middleware as shown below , please help me what I have to do to solve this issue

   app.UsePerTenant<AppTenant>((ctx, builder) =>
            {
                builder.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
                {
                    Authority = ctx.Tenant.Authority,
                    AllowedScopes = { "api1" },
                    AutomaticAuthenticate = true,
                    AutomaticChallenge = true,
                    RequireHttpsMetadata = false,
                    AuthenticationScheme=$"{ctx.Tenant.Id}.Cookies",

                });
                builder.UseCookieAuthentication(new CookieAuthenticationOptions()
                {
                    AuthenticationScheme = $"{ctx.Tenant.Id}.Cookies",
                    //LoginPath = new PathString("/account/login"),
                    //AccessDeniedPath = new PathString("/account/forbidden"),
                    AutomaticAuthenticate = false,
                    AutomaticChallenge = false,
                    CookieName = $"{ctx.Tenant.Id}.AspNet.Cookies"
                });

                builder.UseStaticFiles();
                builder.UseIdentity();
                builder.UseIdentityServer();

                builder.UseMvc(routes =>
                {
                    routes.MapRoute(
                        name: "default",
                        template: "{controller=Home}/{action=Index}/{id?}");
                });
            });

**Comment by joeaudette** [comment]
I would change the order of the middleware

     builder.UseCookieAuthentication...
     builder.UseIdentity()
     builder.UseIdentityServer()
     builder.UseIdentityServerAuthentication...
     builder.UseMvc...

I would put app.UseStaticFiles before  app.UsePerTenant, not inside there
probably also app.UseMvc should not be per tenant, it should come after the end of app.UserPerTenant

**Comment by learntecno** [comment]
@joeaudette 
Thank you! I did the same but I am getting the error

InvalidOperationException: **No authentication handler is configured to handle the scheme: Identity.Application**
Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager+<SignInAsync>d__14.MoveNext()

**Comment by learntecno** [comment]
@joeaudette  
                       I tried with changing Authentication schema and without. but I am getting error
**InvalidOperationException: No authentication handler is configured to handle the scheme: Identity.Application**
   
app.UseMultitenancy<AppTenant>();
            app.UseStaticFiles();

            app.UsePerTenant<AppTenant>((ctx, builder) =>
            {
                builder.UseCookieAuthentication(new CookieAuthenticationOptions()
                {
                    //AuthenticationScheme = $"Cookies",
                    AutomaticAuthenticate = false,
                    AutomaticChallenge = true,
                    CookieName = $"{ctx.Tenant.Id}.AspNet.Cookies"
                });
                app.UseIdentity();
                app.UseIdentityServer();
                builder.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
                {
                    Authority = ctx.Tenant.Authority,
                    AllowedScopes = { "api1" },
                    AutomaticAuthenticate = true,
                    AutomaticChallenge = true,
                    RequireHttpsMetadata = false,
                  });               
            }); 
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

**Comment by joeaudette** [comment]
The problem is because IOptions of IdentityOptions is a singleton used everywhere throughout asp.net identity and it has its own settings for cookiename and authscheme that conflict with the per tenant values you defined in startup. I solved it in my project using a [custom implementation of IOptions of IdentityOptions ](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Identity/SiteIdentityOptionsResolver.cs) that returns the tenant specific settings

**Comment by learntecno** [comment]
@joeaudette 
I have did the same , I could see in the debug it hitting SiteIdentityOptionsResolver that calls SetupAppCookie as you pointed earlier. I could see the schema is changed to "Application"
but  I am getting the error 
InvalidOperationException: No authentication handler is configured to handle the scheme: **Application**

public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, IApplicationLifetime applicationLifetime)
        {
            app.UseMultitenancy<AppTenant>();
            app.UseStaticFiles();

            app.UsePerTenant<AppTenant>((ctx, builder) =>
            {
                app.UseIdentity();
                app.UseIdentityServer();
                builder.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
                {
                    Authority = ctx.Tenant.Authority,
                    AllowedScopes = { "api1" },
                    AutomaticAuthenticate = true,
                    AutomaticChallenge = true,
                    RequireHttpsMetadata = false,
                    AuthenticationScheme = $"{ctx.Tenant.Id}.Cookies"
                });
            }); 
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
 public void ConfigureServices(IServiceCollection services, IConfigurationRoot configuration)
        {
            services.AddOptions();
            services.AddMultitenancy<AppTenant, CachingAppTenantResolver>();
            services.Configure<MultitenancyOptions>(configuration.GetSection("Multitenancy"));

            services.AddSingleton<SiteAuthCookieValidator, SiteAuthCookieValidator>();
            services.AddSingleton<IOptions<IdentityOptions>, SiteIdentityOptionsResolver>();
  }

**Comment by joeaudette** [comment]
you need to make the auth scheme the same in both places, ie in Startup where you configure the cookie auth must match what is returned from the resolver.

**Comment by learntecno** [comment]
@joeaudette 
Thank you so much , this time no error but I am getting different behavior
1) in the login screen providing   username and password and hitting login button, it validating the user but in user status UI could not able to identify the user is logged in , do we need to customize signInManagermanager since we are changing the cookie name and schema.

2) I am using oidc-client.min.js  in client app connecting Identity Server 4

GET http://localhost:6001/.well-known/openid-configuration 404 (Not Found)


In the startup.cs
app.UsePerTenant<AppTenant>((ctx, builder) =>
            {
                builder.UseCookieAuthentication(new CookieAuthenticationOptions()
                {
                    AuthenticationScheme = $"Application",
                    AutomaticAuthenticate = false,
                    AutomaticChallenge = false,
                    CookieName = $"{"Application"}-{ctx.Tenant.Id}"
                });
                app.UseIdentity();
               app.UseIdentityServer();
                builder.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
                {
                    Authority = ctx.Tenant.Authority,
                    AllowedScopes = { "api1" },
                    AutomaticAuthenticate = true,
                    AutomaticChallenge = true,
                    RequireHttpsMetadata = false,
                    //AuthenticationScheme = $"{ctx.Tenant.Id}.Cookies"
                });
            });

**Comment by joeaudette** [comment]
I think AutomaticChallenge and AutomaticAuthenticate should both be true on the ApplicationCookie, you have them as false

**Comment by joeaudette** [comment]
and again it should be the same in the resolver, the cookieoptions must be the same in both places

**Comment by joeaudette** [comment]
I'm not sure about AutomaticChallenge and AutomaticAuthenticate on the IdentityServerAuthenticationOptions. I'm not setting those on mine just letting it use whatever the defaults are and it works for me. but on the main application cookie they should be true
