### ISSUE TITLE
Skip checking tenant id, everytime, attaching tenant Id to natively to user object

### ISSUE THREAD

**Issue by weedkiller** [saaskit/saaskit#58]
Hi, in the context where the tennats are sharing the same database, I was going through this and I had a concern, if the source is tampered _where the tenant Id was edited_, would the other tenants data be corrupted/exposed.

Would it be possible to natively extended/integrate the user object to include the tenant Id, where we can transparently continue the operations on the serverside, without have to check the tenant every-time before a save or edit?

Thanks

**Comment by benfoster** [comment]
If you want true isolation, use a separate database per tenant. 

Otherwise, if you're using Entity Framework, you could hook into the EF lifecycle to set the tenant ID before your objects are saved. I don't have exact details on this - just google EF Lifecycle handler and if it supports DI, you should be golden.
