### ISSUE TITLE
Showing another logged in user details when going to login to a tenant

### ISSUE THREAD

**Issue by kodithuwa** [saaskit/saaskit#61]
Hi,
it is showing previous logged in user details , when i am going to login another tenant.
still, i am trying to resolve it. but,  doesn't meet any fix.
Thanks

**Comment by benfoster** [comment]
Are both tenants on the same domain? Can you post your configuration code?

**Comment by kodithuwa** [comment]
Hi,
Thank you for your response.
i didnt change any configurations. what i did as follows:
1.Change connectionstrings of appsettings for each tenant 
2.Use **dotnet run**  and open http://localhost:60000(tenant1)  http://localhost:60002(tenant2)
3.Register an user in tenant1 and login to tenant1

after refresh tenant2 url , all the links (home,about, contact) can be browsed. it seems SignInManager.IsSignedIn(User) method always true.

**Comment by skimmilk** [comment]
That's because HTTP cookies are not port-specific, only domain-specific.  Look at [this SO article](http://stackoverflow.com/questions/1612177/are-http-cookies-port-specific) for more information.  Basically, the browser treats cookies from localhost:60000 and localhost:60001 as the same -- your cookie based authentication token is used on both URLs and therefore you are shown up as logged in to both URLS.  This should never be a problem in production, but for dev testing, try following [this article](http://benfoster.io/blog/aspnet-core-multi-tenant-middleware-pipelines) for better separating of localhost domains.

**Comment by kodithuwa** [comment]
many thanks, i already checked on local IIS server and it is working
