### ISSUE TITLE
Thread Safe HttpContext Access

### ISSUE THREAD

**Issue by codyskidmore** [saaskit/saaskit#98]
I read through the source for AppTenantResolver and noticed the following:
`        public Task<TenantContext<AppTenant>> ResolveAsync(HttpContext context)
        {
            string tenantName = null;
            TenantContext<AppTenant> tenantContext = null;

            if (mappings.TryGetValue(context.Request.Host.Value, out tenantName))
            {
                tenantContext = new TenantContext<AppTenant>(
                    new AppTenant { Name = tenantName, Hostnames = new[] { context.Request.Host.Value } });

                tenantContext.Properties.Add("Created", DateTime.UtcNow);
            }

            return Task.FromResult(tenantContext);
        }`

SynchronizationContext is not plugged directly into ASP.NET Core's pipeline in ASP.NET Core, so HttpContext is not thread safe (read or write) any longer. Does locking code exist elsewhere exist to prevent HttpContext related bugs?

**Comment by RickBlouch** [comment]
That usage should be fine though because it's being fed from the `HttpContext` passed into the `Invoke` method on the [Middleware](https://github.com/saaskit/saaskit/blob/master/src/SaasKit.Multitenancy/Internal/TenantResolutionMiddleware.cs).

Try following the call chain up to the Middleware and see if you agree with me.
